server:
  port: 8277
  servlet:
    session:
      # セッションのタイムアウト
      timeout: 22m
      cookie:
        http-only: true
        secure: true
  compression:
    enabled: true
    min-response-size: 1024
  # Tomcat => Jetty へ切り替え
  jetty:
    # スレッドプールの設定（Tomcat の threads.max/min-spare に対応）
    threads:
      min: 2     # Tomcat の min-spare 相当
      max: 20    # Tomcat の max  相当
      idle-timeout: 67s
    accesslog:
      enabled: false
spring:
  application:
    name: nasb1995edv2
  servlet:
    multipart:
      max-file-size: 2MB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://52.198.76.7:5432/nasb1995
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      max-lifetime: 1200000
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    open-in-view: false
  freemarker:
    charset: UTF-8
    allow-request-override: true
    allow-session-override: true
    template-loader-path: classpath:/templates/
    suffix: .ftlh
    settings:
      {datetimeFormat: yyyy-MM-dd HH:mm:ss, templateUpdateDelay: 0ms}
  profiles:
    active: prod